// packages/react-file-preview/src/FilePreviewModal.tsx
import { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { PreviewFileInput, CustomRenderer } from './types';
import { FilePreviewContent } from './FilePreviewContent';
import type { Locale, Messages, Theme, CustomRendererEventPayload, PreviewFile, RequestHandler, RequestInitFactory, ShouldFetchAsBlob } from '@eternalheart/file-preview-core';

interface FilePreviewModalProps {
  files: PreviewFileInput[];
  currentIndex: number;
  isOpen: boolean;
  onClose: () => void;
  onNavigate?: (index: number) => void;
  customRenderers?: CustomRenderer[];
  /** 国际化语言，默认 'zh-CN' */
  locale?: Locale;
  /** 用户自定义翻译字典 */
  messages?: Partial<Record<Locale, Partial<Messages>>>;
  /** 无头模式：隐藏工具栏和导航箭头 */
  headless?: boolean;
  /** 主题模式，默认 'dark' */
  theme?: Theme;
  /** 自定义渲染器派发的事件出口 */
  onCustomEvent?: (event: CustomRendererEventPayload) => void;
  /** 自定义 RequestInit（或工厂函数）：注入 Authorization 等鉴权头 */
  requestInit?: RequestInitFactory;
  /** 自定义请求处理器：完全接管库内 fetch */
  requestHandler?: RequestHandler;
  /** 返回 true 时，对应文件先 fetcher→blob URL 后喂给 image/video/audio/pdf 等 renderer */
  shouldFetchAsBlob?: ShouldFetchAsBlob;
  /** 自定义下载回调；不传时库内默认通过 fetcher 拉 Blob 触发下载 */
  onDownload?: (file: PreviewFile) => void | Promise<void>;
  /** 是否显示关闭按钮，默认根据 mode 决定（modal: true） */
  showClose?: boolean;
  /** 是否显示下载按钮，默认 true */
  showDownload?: boolean;
  /** 是否显示文件导航箭头，默认 true */
  showNavigation?: boolean;
  /** 是否循环导航文件，默认 false */
  loopNavigation?: boolean;
}

export const FilePreviewModal: React.FC<FilePreviewModalProps> = ({
  files,
  currentIndex,
  isOpen,
  onClose,
  onNavigate,
  customRenderers = [],
  locale,
  messages,
  headless,
  theme = 'dark',
  onCustomEvent,
  requestInit,
  requestHandler,
  shouldFetchAsBlob,
  onDownload,
  showClose,
  showDownload,
  showNavigation,
  loopNavigation,
}) => {
  const [systemDark, setSystemDark] = useState(() =>
    typeof window !== 'undefined'
      ? window.matchMedia('(prefers-color-scheme: dark)').matches
      : true,
  );

  useEffect(() => {
    if (theme !== 'auto') return;
    const mql = window.matchMedia('(prefers-color-scheme: dark)');
    const handler = (e: MediaQueryListEvent) => setSystemDark(e.matches);
    mql.addEventListener('change', handler);
    return () => mql.removeEventListener('change', handler);
  }, [theme]);

  const resolvedTheme = theme === 'auto' ? (systemDark ? 'dark' : 'light') : theme;

  // 锁定 body 滚动
  useEffect(() => {
    if (isOpen) {
      const originalOverflow = document.body.style.overflow;
      const originalPaddingRight = document.body.style.paddingRight;

      const scrollbarWidth = window.innerWidth - document.documentElement.clientWidth;

      document.body.style.overflow = 'hidden';
      if (scrollbarWidth > 0) {
        document.body.style.paddingRight = `${scrollbarWidth}px`;
      }

      return () => {
        document.body.style.overflow = originalOverflow;
        document.body.style.paddingRight = originalPaddingRight;
      };
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const modalContent = (
    <div className="rfp-root" data-theme={resolvedTheme}>
      <div
        className="rfp-fixed rfp-inset-0 rfp-z-[9999] rfp-flex rfp-items-center rfp-justify-center rfp-backdrop-blur-md rfp-overflow-hidden rfp-bg-surface-overlay"
        onClick={onClose}
        onWheel={(e) => e.stopPropagation()}
      >
        <div
          className="rfp-relative rfp-w-full rfp-h-full"
          onClick={(e) => e.stopPropagation()}
        >
          <FilePreviewContent
            mode="modal"
            files={files}
            currentIndex={currentIndex}
            onClose={onClose}
            onNavigate={onNavigate}
            customRenderers={customRenderers}
            locale={locale}
            messages={messages}
            headless={headless}
            theme={theme}
            onCustomEvent={onCustomEvent}
            requestInit={requestInit}
            requestHandler={requestHandler}
            shouldFetchAsBlob={shouldFetchAsBlob}
            onDownload={onDownload}
            showClose={showClose}
            showDownload={showDownload}
            showNavigation={showNavigation}
            loopNavigation={loopNavigation}
          />
        </div>
      </div>
    </div>
  );

  return createPortal(modalContent, document.body);
};

// packages/vue-file-preview/src/FilePreviewModal.vue
<script setup lang="ts">
import { watch, ref, onBeforeUnmount, computed } from 'vue';
import type { PreviewFile, PreviewFileInput, Locale, Messages, Theme, CustomRendererEventPayload, RequestHandler, RequestInitFactory, ShouldFetchAsBlob } from '@eternalheart/file-preview-core';
import type { CustomRenderer } from './types';
import FilePreviewContent from './FilePreviewContent.vue';
import { useScrollLock } from './composables/useScrollLock';

interface Props {
  files: PreviewFileInput[];
  currentIndex: number;
  isOpen: boolean;
  customRenderers?: CustomRenderer[];
  /** 语言 */
  locale?: Locale;
  /** 自定义翻译字典 */
  messages?: Partial<Record<Locale, Partial<Messages>>>;
  /** 无头模式：隐藏工具栏和导航箭头 */
  headless?: boolean;
  /** 主题模式，默认 'dark' */
  theme?: Theme;
  /** 自定义 RequestInit（或工厂函数）：注入 Authorization 等鉴权头 */
  requestInit?: RequestInitFactory;
  /** 自定义请求处理器：完全接管库内 fetch */
  requestHandler?: RequestHandler;
  /** 返回 true 时，对应文件先 fetcher→blob URL 后喂给 image/video/audio/pdf 等 renderer */
  shouldFetchAsBlob?: ShouldFetchAsBlob;
  /** 自定义下载回调；不传时库内默认通过 fetcher 拉 Blob 触发下载 */
  onDownload?: (file: PreviewFile) => void | Promise<void>;
  /** 是否显示关闭按钮，默认根据 mode 决定（modal: true） */
  showClose?: boolean;
  /** 是否显示下载按钮，默认 true */
  showDownload?: boolean;
  /** 是否显示文件导航箭头，默认 true */
  showNavigation?: boolean;
  /** 是否循环导航文件，默认 false */
  loopNavigation?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  customRenderers: () => [],
  locale: undefined,
  messages: undefined,
  headless: false,
  theme: 'dark',
  requestInit: undefined,
  requestHandler: undefined,
  shouldFetchAsBlob: undefined,
  onDownload: undefined,
  showClose: undefined,
  showDownload: true,
  showNavigation: true,
  loopNavigation: false,
});

const emit = defineEmits<{
  (e: 'close'): void;
  (e: 'navigate', index: number): void;
  (e: 'custom-event', payload: CustomRendererEventPayload): void;
}>();

const { lock, unlock } = useScrollLock(() => props.isOpen);

watch(
  () => props.isOpen,
  (open) => {
    if (open) lock();
    else unlock();
  }
);

const systemDark = ref(
  typeof window !== 'undefined'
    ? window.matchMedia('(prefers-color-scheme: dark)').matches
    : true,
);

let mediaQueryCleanup: (() => void) | null = null;

watch(
  () => props.theme,
  (theme) => {
    if (mediaQueryCleanup) {
      mediaQueryCleanup();
      mediaQueryCleanup = null;
    }
    if (theme === 'auto') {
      const mql = window.matchMedia('(prefers-color-scheme: dark)');
      const handler = (e: MediaQueryListEvent) => { systemDark.value = e.matches; };
      mql.addEventListener('change', handler);
      mediaQueryCleanup = () => mql.removeEventListener('change', handler);
    }
  },
  { immediate: true },
);

onBeforeUnmount(() => {
  if (mediaQueryCleanup) mediaQueryCleanup();
});

const resolvedTheme = computed(() =>
  props.theme === 'auto' ? (systemDark.value ? 'dark' : 'light') : props.theme,
);

const handleBackdropClick = () => emit('close');
const handleContentClick = (e: MouseEvent) => e.stopPropagation();
const handleWheel = (e: WheelEvent) => e.stopPropagation();
</script>

<template>
  <Teleport to="body">
    <div v-if="isOpen" class="vfp-root" :data-theme="resolvedTheme">
        <div
          class="vfp-fixed vfp-inset-0 vfp-z-[9999] vfp-flex vfp-items-center vfp-justify-center vfp-backdrop-blur-md vfp-overflow-hidden vfp-bg-surface-overlay"
          @click="handleBackdropClick"
          @wheel="handleWheel"
        >
          <div class="vfp-relative vfp-w-full vfp-h-full" @click="handleContentClick">
            <FilePreviewContent
              mode="modal"
              :files="files"
              :current-index="currentIndex"
              :custom-renderers="customRenderers"
              :locale="locale"
              :messages="messages"
              :headless="headless"
              :theme="theme"
              :request-init="requestInit"
              :request-handler="requestHandler"
              :should-fetch-as-blob="shouldFetchAsBlob"
              :on-download="onDownload"
              :on-close="() => emit('close')"
              :show-close="showClose"
              :show-download="showDownload"
              :show-navigation="showNavigation"
              :loop-navigation="loopNavigation"
              @close="emit('close')"
              @navigate="(i) => emit('navigate', i)"
              @custom-event="(p) => emit('custom-event', p)"
            />
          </div>
        </div>
    </div>
  </Teleport>
</template>
