// packages/angular-file-preview/src/renderers/Zip/tree-item.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
} from '@angular/core';
import {
  Folder,
  FolderOpen,
  FileText,
  FileImage,
  FileCode,
  File as FileIcon,
  ChevronRight,
} from 'lucide-angular';
import { LucideAngularModule } from 'lucide-angular';
import type { LucideIconData } from 'lucide-angular';
import { formatFileSize, getFileType, type ZipTreeNode } from '../../fp-core';

@Component({
  selector: 'afp-zip-tree-item',
  standalone: true,
  imports: [LucideAngularModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (node().isDir) {
      <div>
        <button
          type="button"
          class="tree-row dir-row"
          [style]="padStyle()"
          (click)="toggle.emit(node().path)"
          (mouseenter)="handleEnter($event)"
          (mouseleave)="leave.emit()"
        >
          <i-lucide
            [img]="chevronRight"
            class="afp-w-3.5 afp-h-3.5 afp-flex-shrink-0 afp-transition-transform"
            [class.afp-rotate-90]="isOpen()"
          />
          <i-lucide
            [img]="isOpen() ? folderOpen : folder"
            class="afp-w-4 afp-h-4 afp-flex-shrink-0 afp-text-amber-300/80"
          />
          <span class="afp-truncate afp-flex-1 afp-min-w-0">{{ node().name || '/' }}</span>
        </button>
        @if (isOpen() && node().children) {
          @for (child of node().children; track child.path) {
            <afp-zip-tree-item
              [node]="child"
              [depth]="depth() + 1"
              [selectedPath]="selectedPath()"
              [expanded]="expanded()"
              (toggle)="toggle.emit($event)"
              (select)="select.emit($event)"
              (hover)="hover.emit($event)"
              (leave)="leave.emit()"
            />
          }
        }
      </div>
    } @else {
      <button
        type="button"
        class="tree-row file-row"
        [class.selected]="isSelected()"
        [style]="padStyle()"
        (click)="select.emit(node())"
        (mouseenter)="handleEnter($event)"
        (mouseleave)="leave.emit()"
      >
        <span class="afp-w-3.5 afp-h-3.5 afp-flex-shrink-0"></span>
        <i-lucide [img]="fileIcon()" class="afp-w-4 afp-h-4 afp-flex-shrink-0 afp-text-fg-tertiary" />
        <span class="afp-flex-1 afp-truncate afp-min-w-0">{{ node().name }}</span>
        <span class="afp-text-xs afp-text-fg-disabled afp-flex-shrink-0 afp-ml-2">{{ formatFileSize(node().size) }}</span>
      </button>
    }
  `,
  styles: [`
    :host { display: block; width: 100%; }
    .tree-row {
      width: 100%;
      display: flex;
      align-items: center;
      gap: 0.375rem;
      padding-top: 0.375rem;
      padding-bottom: 0.375rem;
      padding-right: 0.5rem;
      text-align: left;
      font-size: 0.875rem;
      min-height: 40px;
      background: transparent;
      border: 0;
      cursor: pointer;
    }
    .dir-row {
      color: var(--fp-fg-secondary);
    }
    .file-row {
      color: var(--fp-fg-secondary);
    }
    .tree-row:hover {
      background: var(--fp-surface-1);
    }
    .file-row.selected {
      background: var(--fp-line);
      color: var(--fp-fg-primary);
    }
    .file-row.selected .afp-text-fg-tertiary,
    .file-row.selected .afp-text-fg-disabled {
      color: var(--fp-fg-secondary);
    }
  `],
})
export class ZipTreeItem {
  node = input.required<ZipTreeNode>();
  depth = input.required<number>();
  selectedPath = input<string | null>(null);
  expanded = input.required<Set<string>>();

  toggle = output<string>();
  select = output<ZipTreeNode>();
  hover = output<{ text: string; rect: DOMRect }>();
  leave = output<void>();

  protected readonly chevronRight = ChevronRight;
  protected readonly folder = Folder;
  protected readonly folderOpen = FolderOpen;
  protected readonly formatFileSize = formatFileSize;

  readonly padStyle = computed(() => ({ paddingLeft: `${this.depth() * 14 + 10}px` }));
  readonly isOpen = computed(() => this.expanded().has(this.node().path));
  readonly isSelected = computed(() => this.selectedPath() === this.node().path);
  readonly fileIcon = computed<LucideIconData>(() => {
    const name = this.node().name;
    const ft = getFileType({ id: '', name, url: '', type: '' });
    if (ft === 'image') return FileImage;
    if (ft === 'text' || ft === 'markdown' || ft === 'json' || ft === 'csv' || ft === 'xml' || ft === 'subtitle') {
      return (name.endsWith('.md') || name.endsWith('.markdown')) ? FileText : FileCode;
    }
    return FileIcon;
  });

  handleEnter(e: MouseEvent): void {
    const rect = (e.currentTarget as HTMLElement).getBoundingClientRect();
    this.hover.emit({ text: this.node().name || '/', rect });
  }
}

// packages/vue-file-preview/src/renderers/Zip/TreeItem.vue
<script setup lang="ts">
import { computed } from 'vue';
import {
  Folder,
  FolderOpen,
  FileText,
  FileImage,
  FileCode,
  File as FileIcon,
  ChevronRight,
} from 'lucide-vue-next';
import { formatFileSize, getFileType, type ZipTreeNode } from '@eternalheart/file-preview-core';

const props = defineProps<{
  node: ZipTreeNode;
  depth: number;
  selectedPath: string | null;
  expanded: Set<string>;
}>();

const emit = defineEmits<{
  (e: 'toggle', path: string): void;
  (e: 'select', node: ZipTreeNode): void;
  (e: 'hover', text: string, rect: DOMRect): void;
  (e: 'leave'): void;
}>();

const padStyle = computed(() => ({ paddingLeft: `${props.depth * 14 + 10}px` }));
const isOpen = computed(() => props.expanded.has(props.node.path));
const isSelected = computed(() => props.selectedPath === props.node.path);

const fileIcon = computed(() => {
  const ft = getFileType({ id: '', name: props.node.name, url: '', type: '' });
  if (ft === 'image') return FileImage;
  if (ft === 'text' || ft === 'markdown' || ft === 'json' || ft === 'csv' || ft === 'xml' || ft === 'subtitle') {
    return (props.node.name.endsWith('.md') || props.node.name.endsWith('.markdown')) ? FileText : FileCode;
  }
  return FileIcon;
});

const handleEnter = (e: MouseEvent) => {
  const rect = (e.currentTarget as HTMLElement).getBoundingClientRect();
  emit('hover', props.node.name || '/', rect);
};

const handleLeave = () => emit('leave');
</script>

<template>
  <div v-if="node.isDir">
    <button
      type="button"
      class="tree-row dir-row"
      :style="padStyle"
      @click="emit('toggle', node.path)"
      @mouseenter="handleEnter"
      @mouseleave="handleLeave"
    >
      <ChevronRight
        class="vfp-w-3.5 vfp-h-3.5 vfp-flex-shrink-0 vfp-transition-transform"
        :class="{ 'vfp-rotate-90': isOpen }"
      />
      <component
        :is="isOpen ? FolderOpen : Folder"
        class="vfp-w-4 vfp-h-4 vfp-flex-shrink-0 vfp-text-amber-300/80"
      />
      <span class="vfp-truncate vfp-flex-1 vfp-min-w-0">{{ node.name || '/' }}</span>
    </button>
    <template v-if="isOpen && node.children">
      <ZipTreeItem
        v-for="child in node.children"
        :key="child.path"
        :node="child"
        :depth="depth + 1"
        :selected-path="selectedPath"
        :expanded="expanded"
        @toggle="(p) => emit('toggle', p)"
        @select="(n) => emit('select', n)"
        @hover="(t, r) => emit('hover', t, r)"
        @leave="emit('leave')"
      />
    </template>
  </div>
  <button
    v-else
    type="button"
    class="tree-row file-row"
    :class="{ selected: isSelected }"
    :style="padStyle"
    @click="emit('select', node)"
    @mouseenter="handleEnter"
    @mouseleave="handleLeave"
  >
    <span class="vfp-w-3.5 vfp-h-3.5 vfp-flex-shrink-0" />
    <component :is="fileIcon" class="vfp-w-4 vfp-h-4 vfp-flex-shrink-0 vfp-text-fg-tertiary" />
    <span class="vfp-flex-1 vfp-truncate vfp-min-w-0">{{ node.name }}</span>
    <span class="vfp-text-xs vfp-text-fg-disabled vfp-flex-shrink-0 vfp-ml-2">{{ formatFileSize(node.size) }}</span>
  </button>
</template>

<script lang="ts">
export default { name: 'ZipTreeItem' };
</script>

<style scoped>
.tree-row {
  width: 100%;
  display: flex;
  align-items: center;
  gap: 0.375rem;
  padding-top: 0.375rem;
  padding-bottom: 0.375rem;
  padding-right: 0.5rem;
  text-align: left;
  font-size: 0.875rem;
  background: transparent;
  border: 0;
  cursor: pointer;
  min-height: 40px;
}
.dir-row {
  color: var(--fp-fg-secondary);
}
.file-row {
  color: var(--fp-fg-secondary);
}
.tree-row:hover {
  background: var(--fp-surface-1);
}
.file-row.selected {
  background: var(--fp-line);
  color: var(--fp-fg-primary);
}
.file-row.selected .vfp-text-fg-tertiary,
.file-row.selected .vfp-text-fg-disabled {
  color: var(--fp-fg-secondary);
}
</style>
