// packages/react-file-preview/src/components/ResizableSplit.tsx
import React, { useEffect, useImperativeHandle, useRef, useState, useCallback, forwardRef } from 'react';

export interface ResizableSplitProps {
  /** 左侧内容 */
  left: React.ReactNode;
  /** 右侧内容 */
  right: React.ReactNode;
  /** 左侧初始宽度（px）；传入 storageKey 时会从 localStorage 读取 */
  initialLeftWidth?: number;
  /** 左侧最小宽度（px） */
  minLeftWidth?: number;
  /** 左侧最大宽度（px），同时不超过 `容器宽 - minRightWidth - 分隔线宽` */
  maxLeftWidth?: number;
  /** 右侧至少保留的宽度（px） */
  minRightWidth?: number;
  /** localStorage 持久化 key；不传则不持久化 */
  storageKey?: string;
  /** 启用横向拖动的媒体查询，默认 `(min-width: 768px)` */
  desktopMedia?: string;
  /** 容器额外类名 */
  className?: string;
  /** 移动端使用 Tab 切换而非上下堆叠 */
  mobileTabMode?: boolean;
  /** Tab 模式下左侧标题 */
  leftTabLabel?: string;
  /** Tab 模式下右侧标题 */
  rightTabLabel?: string;
}

export interface ResizableSplitHandle {
  switchTab: (tab: 'left' | 'right') => void;
}

/**
 * 通用可拖动分隔布局：
 * - 桌面端（由 `desktopMedia` 判定）横向分两栏，中间分隔线可左右拖动调整左栏宽度
 * - 移动端默认退化为上下堆叠（不显示分隔线）
 * - 设置 `mobileTabMode` 时移动端使用 Tab 切换显示
 * - 可选 `storageKey` 将宽度持久化到 localStorage
 */
export const ResizableSplit = forwardRef<ResizableSplitHandle, ResizableSplitProps>(({
  left,
  right,
  initialLeftWidth = 280,
  minLeftWidth = 160,
  maxLeftWidth = 640,
  minRightWidth = 200,
  storageKey,
  desktopMedia = '(min-width: 768px)',
  className = '',
  mobileTabMode = false,
  leftTabLabel = '文件树',
  rightTabLabel = '预览',
}, ref) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const [leftWidth, setLeftWidth] = useState<number>(() => {
    if (storageKey && typeof window !== 'undefined') {
      const saved = Number(window.localStorage.getItem(storageKey));
      if (!isNaN(saved) && saved > 0) return saved;
    }
    return initialLeftWidth;
  });
  const [dragging, setDragging] = useState(false);
  const [isDesktop, setIsDesktop] = useState(false);
  const [containerWide, setContainerWide] = useState(true);
  const [activeTab, setActiveTab] = useState<'left' | 'right'>('left');

  useImperativeHandle(ref, () => ({
    switchTab: (tab) => setActiveTab(tab),
  }), []);

  // 响应式：监听媒体查询
  useEffect(() => {
    if (typeof window === 'undefined') return;
    const mq = window.matchMedia(desktopMedia);
    const handler = () => setIsDesktop(mq.matches);
    handler();
    mq.addEventListener('change', handler);
    return () => mq.removeEventListener('change', handler);
  }, [desktopMedia]);

  useEffect(() => {
    const el = containerRef.current;
    if (!el || typeof ResizeObserver === 'undefined') return;
    const update = () => setContainerWide(el.getBoundingClientRect().width >= minLeftWidth + minRightWidth + 6);
    update();
    const observer = new ResizeObserver(update);
    observer.observe(el);
    return () => observer.disconnect();
  }, [minLeftWidth, minRightWidth]);

  // 拖动
  useEffect(() => {
    if (!dragging) return;
    const handleMove = (e: MouseEvent) => {
      if (!containerRef.current) return;
      const rect = containerRef.current.getBoundingClientRect();
      const x = e.clientX - rect.left;
      const cap = rect.width - minRightWidth - 6;
      const effectiveMax = Math.min(maxLeftWidth, cap);
      const newW = Math.max(minLeftWidth, Math.min(effectiveMax, x));
      setLeftWidth(newW);
    };
    const handleUp = () => setDragging(false);
    window.addEventListener('mousemove', handleMove);
    window.addEventListener('mouseup', handleUp);
    const prevCursor = document.body.style.cursor;
    const prevSelect = document.body.style.userSelect;
    document.body.style.cursor = 'col-resize';
    document.body.style.userSelect = 'none';
    return () => {
      window.removeEventListener('mousemove', handleMove);
      window.removeEventListener('mouseup', handleUp);
      document.body.style.cursor = prevCursor;
      document.body.style.userSelect = prevSelect;
    };
  }, [dragging, minLeftWidth, maxLeftWidth, minRightWidth]);

  // 持久化
  useEffect(() => {
    if (!storageKey || dragging) return;
    try {
      window.localStorage.setItem(storageKey, String(leftWidth));
    } catch {
      // ignore
    }
  }, [leftWidth, storageKey, dragging]);

  const handleDividerDown = useCallback((e: React.MouseEvent) => {
    e.preventDefault();
    setDragging(true);
  }, []);

  // 移动端 Tab 模式
  const desktopLayout = isDesktop && containerWide;

  if (mobileTabMode && !desktopLayout) {
    return (
      <div
        ref={containerRef}
        className={`rfp-w-full rfp-h-full rfp-flex rfp-flex-col rfp-min-h-0 rfp-min-w-0 ${className}`}
      >
        <div className="rfp-flex rfp-flex-shrink-0 rfp-border-b rfp-border-line-weak rfp-bg-surface-toolbar">
          <button
            type="button"
            onClick={() => setActiveTab('left')}
            className={`rfp-flex-1 rfp-py-2.5 rfp-text-sm rfp-transition-colors ${
              activeTab === 'left'
                ? 'rfp-text-fg-primary rfp-border-b-2 rfp-border-fg-primary -rfp-mb-px'
                : 'rfp-text-fg-secondary'
            }`}
          >
            {leftTabLabel}
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('right')}
            className={`rfp-flex-1 rfp-py-2.5 rfp-text-sm rfp-transition-colors ${
              activeTab === 'right'
                ? 'rfp-text-fg-primary rfp-border-b-2 rfp-border-fg-primary -rfp-mb-px'
                : 'rfp-text-fg-secondary'
            }`}
          >
            {rightTabLabel}
          </button>
        </div>
        <div
          className="rfp-flex-1 rfp-min-h-0 rfp-min-w-0 rfp-w-full rfp-overflow-hidden"
          style={{ display: activeTab === 'left' ? undefined : 'none' }}
        >
          {left}
        </div>
        <div
          className="rfp-flex-1 rfp-min-h-0 rfp-min-w-0 rfp-w-full rfp-overflow-hidden"
          style={{ display: activeTab === 'right' ? undefined : 'none' }}
        >
          {right}
        </div>
      </div>
    );
  }

  return (
    <div
      ref={containerRef}
      className={`rfp-w-full rfp-h-full rfp-flex rfp-flex-col md:rfp-flex-row rfp-min-h-0 rfp-min-w-0 ${className}`}
      style={desktopLayout ? undefined : { flexDirection: 'column' }}
    >
      <div
        className="rfp-min-h-0 rfp-min-w-0 rfp-flex-shrink-0 rfp-w-full rfp-max-h-60 md:rfp-h-full md:rfp-max-h-none"
        style={desktopLayout ? { width: `${leftWidth}px` } : undefined}
      >
        {left}
      </div>
      {/* 分隔线：仅桌面显示 */}
      <div
        role="separator"
        aria-orientation="vertical"
        onMouseDown={handleDividerDown}
        className={`rfp-hidden md:rfp-block rfp-relative rfp-w-1.5 rfp-flex-shrink-0 rfp-cursor-col-resize rfp-transition-colors ${
          dragging ? 'rfp-bg-surface-toolbar' : 'rfp-bg-surface-2 hover:rfp-bg-surface-3'
        }`}
        style={desktopLayout ? undefined : { display: 'none' }}
      >
        {/* 加宽命中区，改善拖动体验 */}
        <span className="rfp-absolute rfp-inset-y-0 -rfp-left-1 -rfp-right-1" />
      </div>
      <div className="rfp-flex-1 rfp-min-w-0 rfp-min-h-0 rfp-overflow-hidden">{right}</div>
    </div>
  );
});

ResizableSplit.displayName = 'ResizableSplit';

// packages/vue-file-preview/src/components/ResizableSplit.vue
<script setup lang="ts">
import { ref, computed, onBeforeUnmount, onMounted, watch } from 'vue';

interface Props {
  /** 左侧初始宽度（px）；传入 storageKey 时会从 localStorage 读取 */
  initialLeftWidth?: number;
  /** 左侧最小宽度（px） */
  minLeftWidth?: number;
  /** 左侧最大宽度（px） */
  maxLeftWidth?: number;
  /** 右侧至少保留的宽度（px） */
  minRightWidth?: number;
  /** localStorage 持久化 key */
  storageKey?: string;
  /** 启用横向拖动的媒体查询 */
  desktopMedia?: string;
  /** 移动端使用 Tab 切换而非上下堆叠 */
  mobileTabMode?: boolean;
  /** Tab 模式下左侧标题 */
  leftTabLabel?: string;
  /** Tab 模式下右侧标题 */
  rightTabLabel?: string;
}

const props = withDefaults(defineProps<Props>(), {
  initialLeftWidth: 280,
  minLeftWidth: 160,
  maxLeftWidth: 640,
  minRightWidth: 200,
  desktopMedia: '(min-width: 768px)',
  mobileTabMode: false,
  leftTabLabel: '文件树',
  rightTabLabel: '预览',
});

defineOptions({ name: 'ResizableSplit' });

const containerRef = ref<HTMLDivElement | null>(null);
const leftWidth = ref<number>(
  (() => {
    if (props.storageKey && typeof window !== 'undefined') {
      const saved = Number(window.localStorage.getItem(props.storageKey));
      if (!isNaN(saved) && saved > 0) return saved;
    }
    return props.initialLeftWidth;
  })()
);
const dragging = ref(false);
const isDesktop = ref(false);
const containerWide = ref(true);
const activeTab = ref<'left' | 'right'>('left');

let mq: MediaQueryList | null = null;
let resizeObserver: ResizeObserver | null = null;
const mqHandler = () => {
  if (mq) isDesktop.value = mq.matches;
};

const leftStyle = computed(() =>
  isDesktop.value && containerWide.value ? { width: `${leftWidth.value}px` } : undefined
);
const desktopLayout = computed(() => isDesktop.value && containerWide.value);

const onMove = (e: MouseEvent) => {
  if (!containerRef.value) return;
  const rect = containerRef.value.getBoundingClientRect();
  const x = e.clientX - rect.left;
  const cap = rect.width - props.minRightWidth - 6;
  const effectiveMax = Math.min(props.maxLeftWidth, cap);
  leftWidth.value = Math.max(
    props.minLeftWidth,
    Math.min(effectiveMax, x)
  );
};

const onUp = () => {
  if (!dragging.value) return;
  dragging.value = false;
  window.removeEventListener('mousemove', onMove);
  window.removeEventListener('mouseup', onUp);
  document.body.style.cursor = '';
  document.body.style.userSelect = '';
  if (props.storageKey) {
    try {
      window.localStorage.setItem(props.storageKey, String(leftWidth.value));
    } catch {
      // ignore
    }
  }
};

const onDividerDown = (e: MouseEvent) => {
  e.preventDefault();
  dragging.value = true;
  window.addEventListener('mousemove', onMove);
  window.addEventListener('mouseup', onUp);
  document.body.style.cursor = 'col-resize';
  document.body.style.userSelect = 'none';
};

onMounted(() => {
  if (typeof window !== 'undefined') {
    mq = window.matchMedia(props.desktopMedia);
    mqHandler();
    mq.addEventListener('change', mqHandler);
    const updateSize = () => {
      if (containerRef.value) containerWide.value = containerRef.value.getBoundingClientRect().width >= props.minLeftWidth + props.minRightWidth + 6;
    };
    updateSize();
    resizeObserver = typeof ResizeObserver !== 'undefined' ? new ResizeObserver(updateSize) : null;
    resizeObserver?.observe(containerRef.value!);
  }
});

onBeforeUnmount(() => {
  if (mq) mq.removeEventListener('change', mqHandler);
  resizeObserver?.disconnect();
  resizeObserver = null;
  window.removeEventListener('mousemove', onMove);
  window.removeEventListener('mouseup', onUp);
  if (dragging.value) {
    document.body.style.cursor = '';
    document.body.style.userSelect = '';
  }
});

watch(
  () => props.initialLeftWidth,
  (w) => {
    if (!props.storageKey) leftWidth.value = w;
  }
);

const switchTab = (tab: 'left' | 'right') => {
  activeTab.value = tab;
};

defineExpose({ switchTab });
</script>

<template>
  <div
    ref="containerRef"
    class="vfp-w-full vfp-h-full vfp-flex vfp-flex-col md:vfp-flex-row vfp-min-h-0 vfp-min-w-0"
    :style="desktopLayout ? undefined : { flexDirection: 'column' }"
  >
    <!-- 移动端 Tab 模式 -->
    <template v-if="mobileTabMode && !desktopLayout">
      <div class="vfp-flex vfp-flex-shrink-0 vfp-border-b vfp-border-line-weak vfp-bg-surface-toolbar">
        <button
          type="button"
          class="vfp-flex-1 vfp-py-2.5 vfp-text-sm vfp-transition-colors"
          :class="activeTab === 'left'
            ? 'vfp-text-fg-primary vfp-border-b-2 vfp-border-fg-primary -vfp-mb-px'
            : 'vfp-text-fg-secondary'"
          @click="switchTab('left')"
        >
          {{ leftTabLabel }}
        </button>
        <button
          type="button"
          class="vfp-flex-1 vfp-py-2.5 vfp-text-sm vfp-transition-colors"
          :class="activeTab === 'right'
            ? 'vfp-text-fg-primary vfp-border-b-2 vfp-border-fg-primary -vfp-mb-px'
            : 'vfp-text-fg-secondary'"
          @click="switchTab('right')"
        >
          {{ rightTabLabel }}
        </button>
      </div>
      <div v-show="activeTab === 'left'" class="vfp-flex-1 vfp-min-h-0 vfp-min-w-0 vfp-w-full vfp-overflow-hidden">
        <slot name="left" />
      </div>
      <div v-show="activeTab === 'right'" class="vfp-flex-1 vfp-min-h-0 vfp-min-w-0 vfp-w-full vfp-overflow-hidden">
        <slot name="right" />
      </div>
    </template>

    <!-- 桌面端 / 移动端默认堆叠模式 -->
    <template v-else>
      <div
        class="vfp-min-h-0 vfp-min-w-0 vfp-flex-shrink-0 vfp-w-full vfp-max-h-60 md:vfp-h-full md:vfp-max-h-none"
        :style="leftStyle"
      >
        <slot name="left" />
      </div>
      <div
        role="separator"
        aria-orientation="vertical"
        class="split-divider vfp-hidden md:vfp-block vfp-relative vfp-w-1.5 vfp-flex-shrink-0 vfp-cursor-col-resize vfp-transition-colors"
        :class="dragging ? 'dragging' : ''"
        :style="desktopLayout ? undefined : { display: 'none' }"
        @mousedown="onDividerDown"
      >
        <span class="vfp-absolute vfp-inset-y-0 hit-area" />
      </div>
      <div class="vfp-flex-1 vfp-min-w-0 vfp-min-h-0 vfp-overflow-hidden">
        <slot name="right" />
      </div>
    </template>
  </div>
</template>

<style scoped>
.split-divider {
  background: var(--fp-line-weak);
}
.split-divider:hover {
  background: var(--fp-line);
}
.split-divider.dragging {
  background: var(--fp-line-strong);
}
.hit-area {
  left: -4px;
  right: -4px;
}
</style>
