// packages/angular-file-preview/src/file-preview-modal.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  DestroyRef,
  effect,
  ElementRef,
  inject,
  input,
  output,
} from '@angular/core';
import type {
  CustomRendererEventPayload,
  Locale,
  Messages,
  PreviewFile,
  PreviewFileInput,
  RequestHandler,
  RequestInitFactory,
  ShouldFetchAsBlob,
  Theme,
} from './fp-core';
import type { CustomRenderer } from './types';
import { FilePreviewContent } from './file-preview-content';
import { createSystemDarkSignal, resolveTheme } from './di/theme-mode';

@Component({
  selector: 'FilePreviewModal, afp-file-preview-modal',
  standalone: true,
  imports: [FilePreviewContent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (isOpen()) {
      <div class="afp-root" [attr.data-theme]="resolvedTheme()">
        <div
          class="afp-fixed afp-inset-0 afp-z-[9999] afp-flex afp-items-center afp-justify-center afp-backdrop-blur-md afp-overflow-hidden afp-bg-surface-overlay"
          (click)="close.emit()"
          (wheel)="$event.stopPropagation()"
        >
          <div class="afp-relative afp-w-full afp-h-full" (click)="$event.stopPropagation()">
            <FilePreviewContent
              mode="modal"
              [files]="files()"
              [currentIndex]="currentIndex()"
              [customRenderers]="customRenderers()"
              [locale]="locale()"
              [messages]="messages()"
              [headless]="headless()"
              [theme]="theme()"
              [requestInit]="requestInit()"
              [requestHandler]="requestHandler()"
              [shouldFetchAsBlob]="shouldFetchAsBlob()"
              [onDownload]="onDownload()"
              [showClose]="showClose()"
              [showDownload]="showDownload()"
              [showNavigation]="showNavigation()"
              [loopNavigation]="loopNavigation()"
              (close)="close.emit()"
              (navigate)="navigate.emit($event)"
              (customEvent)="customEvent.emit($event)"
            />
          </div>
        </div>
      </div>
    }
  `,
  styles: [`
    :host { display: contents; }
  `],
})
export class FilePreviewModal {
  files = input.required<PreviewFileInput[]>();
  currentIndex = input.required<number>();
  isOpen = input(false);
  customRenderers = input<CustomRenderer[]>([]);
  locale = input<Locale | undefined>(undefined);
  messages = input<Partial<Record<Locale, Partial<Messages>>> | undefined>(undefined);
  headless = input(false);
  theme = input<Theme>('dark');
  requestInit = input<RequestInitFactory | undefined>(undefined);
  requestHandler = input<RequestHandler | undefined>(undefined);
  shouldFetchAsBlob = input<ShouldFetchAsBlob | undefined>(undefined);
  onDownload = input<((file: PreviewFile) => void | Promise<void>) | undefined>(undefined);
  showClose = input<boolean | undefined>(undefined);
  showDownload = input(true);
  showNavigation = input(true);
  loopNavigation = input(false);

  close = output<void>();
  navigate = output<number>();
  customEvent = output<CustomRendererEventPayload>();

  private readonly host = inject(ElementRef<HTMLElement>);
  private readonly destroyRef = inject(DestroyRef);
  private readonly system = createSystemDarkSignal();
  private originalOverflow = '';
  private originalPaddingRight = '';
  private locked = false;

  readonly resolvedTheme = computed(() => resolveTheme(this.theme(), this.system.systemDark()));

  constructor() {
    effect(() => this.system.bind(this.theme()));
    effect(() => {
      if (this.isOpen()) this.lock();
      else this.unlock();
    });
    effect(() => {
      if (!this.isOpen()) return;
      const el = this.host.nativeElement;
      if (el.parentElement !== document.body) {
        document.body.appendChild(el);
      }
    });
    this.destroyRef.onDestroy(() => {
      this.unlock();
      const el = this.host.nativeElement;
      el.parentElement?.removeChild(el);
    });
  }

  private lock(): void {
    if (this.locked || typeof document === 'undefined') return;
    this.originalOverflow = document.body.style.overflow;
    this.originalPaddingRight = document.body.style.paddingRight;
    const scrollbarWidth = window.innerWidth - document.documentElement.clientWidth;
    document.body.style.overflow = 'hidden';
    if (scrollbarWidth > 0) {
      document.body.style.paddingRight = `${scrollbarWidth}px`;
    }
    this.locked = true;
  }

  private unlock(): void {
    if (!this.locked || typeof document === 'undefined') return;
    document.body.style.overflow = this.originalOverflow;
    document.body.style.paddingRight = this.originalPaddingRight;
    this.locked = false;
  }
}

// packages/react-file-preview/src/FilePreviewModal.tsx
import { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { PreviewFileInput, CustomRenderer } from './types';
import { FilePreviewContent } from './FilePreviewContent';
import type { Locale, Messages, Theme, CustomRendererEventPayload, PreviewFile, RequestHandler, RequestInitFactory, ShouldFetchAsBlob } from '@eternalheart/file-preview-core';

interface FilePreviewModalProps {
  files: PreviewFileInput[];
  currentIndex: number;
  isOpen: boolean;
  onClose: () => void;
  onNavigate?: (index: number) => void;
  customRenderers?: CustomRenderer[];
  /** 国际化语言，默认 'zh-CN' */
  locale?: Locale;
  /** 用户自定义翻译字典 */
  messages?: Partial<Record<Locale, Partial<Messages>>>;
  /** 无头模式：隐藏工具栏和导航箭头 */
  headless?: boolean;
  /** 主题模式，默认 'dark' */
  theme?: Theme;
  /** 自定义渲染器派发的事件出口 */
  onCustomEvent?: (event: CustomRendererEventPayload) => void;
  /** 自定义 RequestInit（或工厂函数）：注入 Authorization 等鉴权头 */
  requestInit?: RequestInitFactory;
  /** 自定义请求处理器：完全接管库内 fetch */
  requestHandler?: RequestHandler;
  /** 返回 true 时，对应文件先 fetcher→blob URL 后喂给 image/video/audio/pdf 等 renderer */
  shouldFetchAsBlob?: ShouldFetchAsBlob;
  /** 自定义下载回调；不传时库内默认通过 fetcher 拉 Blob 触发下载 */
  onDownload?: (file: PreviewFile) => void | Promise<void>;
  /** 是否显示关闭按钮，默认根据 mode 决定（modal: true） */
  showClose?: boolean;
  /** 是否显示下载按钮，默认 true */
  showDownload?: boolean;
  /** 是否显示文件导航箭头，默认 true */
  showNavigation?: boolean;
  /** 是否循环导航文件，默认 false */
  loopNavigation?: boolean;
}

export const FilePreviewModal: React.FC<FilePreviewModalProps> = ({
  files,
  currentIndex,
  isOpen,
  onClose,
  onNavigate,
  customRenderers = [],
  locale,
  messages,
  headless,
  theme = 'dark',
  onCustomEvent,
  requestInit,
  requestHandler,
  shouldFetchAsBlob,
  onDownload,
  showClose,
  showDownload,
  showNavigation,
  loopNavigation,
}) => {
  const [systemDark, setSystemDark] = useState(() =>
    typeof window !== 'undefined'
      ? window.matchMedia('(prefers-color-scheme: dark)').matches
      : true,
  );

  useEffect(() => {
    if (theme !== 'auto') return;
    const mql = window.matchMedia('(prefers-color-scheme: dark)');
    const handler = (e: MediaQueryListEvent) => setSystemDark(e.matches);
    mql.addEventListener('change', handler);
    return () => mql.removeEventListener('change', handler);
  }, [theme]);

  const resolvedTheme = theme === 'auto' ? (systemDark ? 'dark' : 'light') : theme;

  // 锁定 body 滚动
  useEffect(() => {
    if (isOpen) {
      const originalOverflow = document.body.style.overflow;
      const originalPaddingRight = document.body.style.paddingRight;

      const scrollbarWidth = window.innerWidth - document.documentElement.clientWidth;

      document.body.style.overflow = 'hidden';
      if (scrollbarWidth > 0) {
        document.body.style.paddingRight = `${scrollbarWidth}px`;
      }

      return () => {
        document.body.style.overflow = originalOverflow;
        document.body.style.paddingRight = originalPaddingRight;
      };
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const modalContent = (
    <div className="rfp-root" data-theme={resolvedTheme}>
      <div
        className="rfp-fixed rfp-inset-0 rfp-z-[9999] rfp-flex rfp-items-center rfp-justify-center rfp-backdrop-blur-md rfp-overflow-hidden rfp-bg-surface-overlay"
        onClick={onClose}
        onWheel={(e) => e.stopPropagation()}
      >
        <div
          className="rfp-relative rfp-w-full rfp-h-full"
          onClick={(e) => e.stopPropagation()}
        >
          <FilePreviewContent
            mode="modal"
            files={files}
            currentIndex={currentIndex}
            onClose={onClose}
            onNavigate={onNavigate}
            customRenderers={customRenderers}
            locale={locale}
            messages={messages}
            headless={headless}
            theme={theme}
            onCustomEvent={onCustomEvent}
            requestInit={requestInit}
            requestHandler={requestHandler}
            shouldFetchAsBlob={shouldFetchAsBlob}
            onDownload={onDownload}
            showClose={showClose}
            showDownload={showDownload}
            showNavigation={showNavigation}
            loopNavigation={loopNavigation}
          />
        </div>
      </div>
    </div>
  );

  return createPortal(modalContent, document.body);
};
