// packages/vue-file-preview/src/renderers/Zip/index.vue
<script setup lang="ts">
import { ref, computed, watch, onBeforeUnmount, defineAsyncComponent } from 'vue';
import type JSZip from 'jszip';
import {
  loadZip,
  listZipEntries,
  buildZipTree,
  readZipEntryBlob,
  inferMimeType,
  type ZipTreeNode,
} from '@eternalheart/file-preview-core';
import ResizableSplit from '../../components/ResizableSplit.vue';
import TreeItem from './TreeItem.vue';
import { useTranslator } from '../../composables/useTranslator';
import { useFetcher } from '../../composables/useRequest';
import RendererError from '../RendererError.vue';
import { ToolbarEventEmitter } from '../base.types';
import type { RendererHandle } from '../base.types';
import type { ToolbarGroup } from '../toolbar.types';

export interface ZipToolbarStats {
  files: number;
  dirs: number;
  size: number;
}

// 懒加载 FilePreviewContent 以打破循环依赖
const LazyFilePreviewContent = defineAsyncComponent(
  () => import('../../FilePreviewContent.vue')
);

const props = withDefaults(defineProps<{
  url: string;
  /** ZIP 嵌套深度（由 FilePreviewContent 传入） */
  nestingDepth?: number;
}>(), {
  nestingDepth: 0,
});

const emitter = new ToolbarEventEmitter();

const { t } = useTranslator();
const fetcher = useFetcher();

interface SelectedPreview {
  path: string;
  name: string;
  size: number;
  blobUrl: string;
}

interface HoverTipState {
  text: string;
  x: number;
  y: number;
}

const zip = ref<JSZip | null>(null);
const tree = ref<ZipTreeNode | null>(null);
const loading = ref(true);
const error = ref<string | null>(null);
const expanded = ref<Set<string>>(new Set(['']));
const selected = ref<SelectedPreview | null>(null);
const previewLoading = ref(false);
const previewError = ref<string | null>(null);
const hoverTip = ref<HoverTipState | null>(null);
const splitRef = ref<InstanceType<typeof ResizableSplit> | null>(null);
const selectingPath = ref<string | null>(null);

const revokeCurrent = () => {
  if (selected.value?.blobUrl) URL.revokeObjectURL(selected.value.blobUrl);
};

const load = async () => {
  revokeCurrent();
  selected.value = null;
  loading.value = true;
  error.value = null;
  try {
    const res = await fetcher.value(props.url);
    if (!res.ok) throw new Error('加载失败');
    const buf = await res.arrayBuffer();
    const z = await loadZip(buf);
    const entries = listZipEntries(z);
    const root = buildZipTree(entries);
    zip.value = z;
    tree.value = root;
    const init = new Set<string>(['']);
    if (root.children) for (const c of root.children) if (c.isDir) init.add(c.path);
    expanded.value = init;
  } catch (err) {
    console.error(err);
    error.value = t.value('zip.load_failed');
  } finally {
    loading.value = false;
  }
};

watch(() => props.url, (newUrl) => {
  // 只有 URL 有效时才加载（避免空字符串或已 revoke 的 blob URL）
  if (newUrl) load();
}, { immediate: true });
onBeforeUnmount(() => { revokeCurrent(); });

const totalStats = computed<ZipToolbarStats | null>(() => {
  if (!tree.value) return null;
  let files = 0, dirs = 0, size = 0;
  const walk = (n: ZipTreeNode) => {
    if (n.isDir) { if (n.path) dirs++; n.children?.forEach(walk); }
    else { files++; size += n.size; }
  };
  walk(tree.value);
  return { files, dirs, size };
});

// 通知工具栏变化
watch(totalStats, () => emitter.notify());

// 工具栏配置（对齐 React：返回空数组，不显示统计信息）
const getToolbarGroups = (): ToolbarGroup[] => [];

defineExpose<RendererHandle>({
  getToolbarGroups,
  onToolbarChange: (listener) => emitter.subscribe(listener),
});

const handleToggle = (path: string) => {
  const next = new Set(expanded.value);
  if (next.has(path)) next.delete(path);
  else next.add(path);
  expanded.value = next;
};

const handleHover = (text: string, rect: DOMRect) => {
  const maxX = typeof window !== 'undefined' ? window.innerWidth - 328 : rect.right + 8;
  hoverTip.value = { text, x: Math.max(8, Math.min(rect.right + 8, maxX)), y: rect.top + rect.height / 2 };
};
const handleLeave = () => { hoverTip.value = null; };

const handleSelect = async (node: ZipTreeNode) => {
  if (!zip.value || node.isDir || selected.value?.path === node.path || selectingPath.value === node.path) return;
  selectingPath.value = node.path;
  revokeCurrent();
  previewLoading.value = true;
  previewError.value = null;

  try {
    const mime = inferMimeType(node.name);
    const blob = await readZipEntryBlob(zip.value, node.path, mime !== 'application/octet-stream' ? mime : undefined);
    const blobUrl = URL.createObjectURL(blob);
    selected.value = { path: node.path, name: node.name, size: node.size, blobUrl };
    // 移动端切换到预览 tab
    splitRef.value?.switchTab('right');
  } catch (err) {
    console.error(err);
    previewError.value = '条目读取失败';
  } finally {
    previewLoading.value = false;
    if (selectingPath.value === node.path) selectingPath.value = null;
  }
};

/** 为嵌入的 FilePreviewContent 构建 files 数组 */
const previewFiles = computed(() => {
  if (!selected.value) return [];
  return [{ name: selected.value.name, url: selected.value.blobUrl, type: inferMimeType(selected.value.name) }];
});
</script>

<template>
  <div v-if="loading" class="vfp-flex vfp-items-center vfp-justify-center vfp-w-full vfp-h-full">
    <div class="vfp-w-12 vfp-h-12 vfp-border-4 vfp-border-line-strong vfp-border-t-spinner-head vfp-rounded-full vfp-animate-spin" />
  </div>

  <RendererError v-else-if="error || !tree" :message="error || t('zip.parse_failed')" />

  <template v-else>
    <ResizableSplit
      ref="splitRef"
      :initial-left-width="280"
      :min-left-width="180"
      :max-left-width="560"
      storage-key="vfp-zip-split-left"
      mobile-tab-mode
      left-tab-label="文件树"
      right-tab-label="预览"
    >
      <template #left>
        <div class="vfp-w-full vfp-h-full vfp-overflow-auto">
          <TreeItem
            v-for="child in tree.children || []"
            :key="child.path"
            :node="child"
            :depth="0"
            :selected-path="selected?.path ?? null"
            :expanded="expanded"
            @toggle="handleToggle"
            @select="handleSelect"
            @hover="handleHover"
            @leave="handleLeave"
          />
        </div>
      </template>

      <template #right>
        <div class="vfp-w-full vfp-h-full vfp-flex vfp-flex-col">
          <div v-if="!selected" class="vfp-flex-1 vfp-flex vfp-items-center vfp-justify-center vfp-text-fg-muted vfp-text-sm vfp-p-6">
            从左侧选择一个文件以预览
          </div>
          <div v-else-if="previewLoading" class="vfp-flex-1 vfp-flex vfp-items-center vfp-justify-center">
            <div class="vfp-w-8 vfp-h-8 vfp-border-4 vfp-border-line-strong vfp-border-t-spinner-head vfp-rounded-full vfp-animate-spin" />
          </div>
          <div v-else-if="previewError" class="vfp-flex-1 vfp-flex vfp-items-center vfp-justify-center vfp-text-fg-secondary">{{ previewError }}</div>
          <template v-else>
            <div class="vfp-flex-1 vfp-min-h-0 vfp-overflow-hidden vfp-flex vfp-relative vfp-z-0">
              <LazyFilePreviewContent
                mode="embed"
                :files="previewFiles"
                :current-index="0"
                :zip-nesting-depth="nestingDepth + 1"
              />
            </div>
          </template>
        </div>
      </template>
    </ResizableSplit>

    <!-- 文件名 hover tooltip (teleport 到 body 避免被滚动区裁剪) -->
    <Teleport to="body">
      <div
        v-if="hoverTip"
        class="vfp-zip-tip"
        :style="{
          position: 'fixed',
          zIndex: 2147483647,
          pointerEvents: 'none',
          display: 'block',
          transform: 'translateY(-50%)',
          padding: '4px 8px',
          background: 'rgba(0, 0, 0, 0.85)',
          color: '#fff',
          fontSize: '12px',
          lineHeight: 1.5,
          borderRadius: '4px',
          whiteSpace: 'nowrap',
          maxWidth: 'min(320px, calc(100vw - 16px))',
          overflow: 'hidden',
          textOverflow: 'ellipsis',
          boxShadow: '0 2px 8px rgba(0, 0, 0, 0.3)',
          left: hoverTip.x + 'px',
          top: hoverTip.y + 'px',
        }"
      >
        {{ hoverTip.text }}
      </div>
    </Teleport>
  </template>
</template>

// packages/react-file-preview/src/renderers/Zip/index.tsx
import { useState, useEffect, useMemo, useCallback, useRef, lazy, Suspense, forwardRef, useImperativeHandle } from 'react';
import React from 'react';
import { createPortal } from 'react-dom';
import {
  Folder,
  FolderOpen,
  FileText,
  FileImage,
  FileCode,
  File as FileIcon,
  ChevronRight,
} from 'lucide-react';
import { RendererError } from '../RendererError';
import type { RendererHandle } from '../base.types';
import type JSZip from 'jszip';
import {
  loadZip,
  listZipEntries,
  buildZipTree,
  readZipEntryBlob,
  formatFileSize,
  getFileType,
  inferMimeType,
  type ZipTreeNode,
} from '@eternalheart/file-preview-core';
import { ResizableSplit, type ResizableSplitHandle } from '../../components/ResizableSplit';
import { useTranslator } from '../../i18n/LocaleContext';
import { useFetcher } from '../../RequestContext';

export interface ZipToolbarStats {
  files: number;
  dirs: number;
  size: number;
}

// 懒加载 FilePreviewContent 以打破循环依赖
const LazyFilePreviewContent = lazy(() =>
  import('../../FilePreviewContent').then(m => ({ default: m.FilePreviewContent }))
);

interface ZipRendererProps {
  url: string;
  /** ZIP 嵌套深度（由 FilePreviewContent 传入） */
  nestingDepth?: number;
  /** 解析完成后向外回报统计信息（files / dirs / size），供工具栏展示 */
  onStatsChange?: (stats: ZipToolbarStats | null) => void;
}

interface SelectedPreview {
  path: string;
  name: string;
  size: number;
  blobUrl: string;
}

/** 根据文件类型返回树节点图标 */
const resolveIcon = (name: string) => {
  const ft = getFileType({ id: '', name, url: '', type: '' });
  if (ft === 'image') return FileImage;
  if (ft === 'text' || ft === 'markdown' || ft === 'json' || ft === 'csv' || ft === 'xml' || ft === 'subtitle') {
    return name.endsWith('.md') || name.endsWith('.markdown') ? FileText : FileCode;
  }
  return FileIcon;
};

// ---------- Tooltip via portal ----------

interface HoverTipState {
  text: string;
  x: number;
  y: number;
}

// ---------- Tree item ----------

interface TreeItemProps {
  node: ZipTreeNode;
  depth: number;
  selectedPath: string | null;
  expanded: Set<string>;
  onToggle: (path: string) => void;
  onSelect: (node: ZipTreeNode) => void;
  onHover: (text: string, rect: DOMRect) => void;
  onLeave: () => void;
}

const TreeItem: React.FC<TreeItemProps> = ({
  node,
  depth,
  selectedPath,
  expanded,
  onToggle,
  onSelect,
  onHover,
  onLeave,
}) => {
  const isOpen = expanded.has(node.path);
  const isSelected = selectedPath === node.path;
  const pad = { paddingLeft: `${depth * 14 + 10}px` };
  const handleEnter = (e: React.MouseEvent<HTMLElement>) => {
    const rect = (e.currentTarget as HTMLElement).getBoundingClientRect();
    onHover(node.name || '/', rect);
  };

  if (node.isDir) {
    return (
      <>
        <button
          type="button"
          onClick={() => onToggle(node.path)}
          onMouseEnter={handleEnter}
          onMouseLeave={onLeave}
          className="rfp-zip-tree-row rfp-w-full rfp-flex rfp-items-center rfp-gap-1.5 rfp-py-1.5 rfp-pr-2 rfp-text-left rfp-text-fg-secondary hover:rfp-bg-surface-1 rfp-text-sm"
          style={pad}
        >
          <ChevronRight
            className={`rfp-w-3.5 rfp-h-3.5 rfp-flex-shrink-0 rfp-transition-transform ${
              isOpen ? 'rfp-rotate-90' : ''
            }`}
          />
          {isOpen ? (
            <FolderOpen className="rfp-w-4 rfp-h-4 rfp-flex-shrink-0 rfp-text-amber-300/80" />
          ) : (
            <Folder className="rfp-w-4 rfp-h-4 rfp-flex-shrink-0 rfp-text-amber-300/80" />
          )}
          <span className="rfp-truncate rfp-flex-1 rfp-min-w-0">{node.name || '/'}</span>
        </button>
        {isOpen &&
          node.children?.map((child) => (
            <TreeItem
              key={child.path}
              node={child}
              depth={depth + 1}
              selectedPath={selectedPath}
              expanded={expanded}
              onToggle={onToggle}
              onSelect={onSelect}
              onHover={onHover}
              onLeave={onLeave}
            />
          ))}
      </>
    );
  }

  const Icon = resolveIcon(node.name);

  return (
    <button
      type="button"
      onClick={() => onSelect(node)}
      onMouseEnter={handleEnter}
      onMouseLeave={onLeave}
      className={`rfp-zip-tree-row rfp-w-full rfp-flex rfp-items-center rfp-gap-1.5 rfp-py-1.5 rfp-pr-2 rfp-text-left rfp-text-sm ${
        isSelected ? 'rfp-zip-file-row-selected' : 'rfp-text-fg-secondary hover:rfp-bg-surface-1'
      }`}
      style={pad}
    >
      <span className="rfp-w-3.5 rfp-h-3.5 rfp-flex-shrink-0" />
      <Icon className="rfp-w-4 rfp-h-4 rfp-flex-shrink-0 rfp-text-fg-tertiary" />
      <span className="rfp-flex-1 rfp-truncate rfp-min-w-0">{node.name}</span>
      <span className="rfp-text-xs rfp-text-fg-disabled rfp-flex-shrink-0 rfp-ml-2">
        {formatFileSize(node.size)}
      </span>
    </button>
  );
};

// ---------- Main Zip Renderer ----------

export const ZipRenderer = forwardRef<RendererHandle, ZipRendererProps>(({ url, nestingDepth = 0, onStatsChange }, ref) => {
  const t = useTranslator();
  const fetcher = useFetcher();
  const [zip, setZip] = useState<JSZip | null>(null);
  const [tree, setTree] = useState<ZipTreeNode | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [expanded, setExpanded] = useState<Set<string>>(new Set(['']));
  const [selected, setSelected] = useState<SelectedPreview | null>(null);
  const [previewLoading, setPreviewLoading] = useState(false);
  const [previewError, setPreviewError] = useState<string | null>(null);
  const [hoverTip, setHoverTip] = useState<HoverTipState | null>(null);
  const onStatsChangeRef = useRef(onStatsChange);
  const splitRef = useRef<ResizableSplitHandle>(null);
  const selectingPathRef = useRef<string | null>(null);

  useEffect(() => {
    onStatsChangeRef.current = onStatsChange;
  }, [onStatsChange]);

  useEffect(() => {
    // 只有 URL 有效时才加载（避免空字符串或已 revoke 的 blob URL）
    if (!url) return;

    let cancelled = false;
    const load = async () => {
      try {
        setLoading(true);
        setError(null);
        const res = await fetcher(url);
        if (!res.ok) throw new Error('加载失败');
        const buf = await res.arrayBuffer();
        const z = await loadZip(buf);
        if (cancelled) return;
        const entries = listZipEntries(z);
        const root = buildZipTree(entries);
        setZip(z);
        setTree(root);
        const init = new Set<string>(['']);
        if (root.children) {
          for (const c of root.children) if (c.isDir) init.add(c.path);
        }
        setExpanded(init);
      } catch (err) {
        console.error(err);
        if (!cancelled) setError(t('zip.load_failed'));
      } finally {
        if (!cancelled) setLoading(false);
      }
    };
    load();
    return () => {
      cancelled = true;
    };
  }, [url]);

  // 切换文件时回收 blob URL
  useEffect(() => {
    return () => {
      if (selected?.blobUrl) URL.revokeObjectURL(selected.blobUrl);
    };
  }, [selected]);

  const totalStats = useMemo<ZipToolbarStats | null>(() => {
    if (!tree) return null;
    let files = 0;
    let dirs = 0;
    let size = 0;
    const walk = (n: ZipTreeNode) => {
      if (n.isDir) {
        if (n.path) dirs++;
        n.children?.forEach(walk);
      } else {
        files++;
        size += n.size;
      }
    };
    walk(tree);
    return { files, dirs, size };
  }, [tree]);

  // 向外回报 stats
  useEffect(() => {
    onStatsChangeRef.current?.(totalStats);
    return () => {
      onStatsChangeRef.current?.(null);
    };
  }, [totalStats]);

  const handleToggle = useCallback((path: string) => {
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(path)) next.delete(path);
      else next.add(path);
      return next;
    });
  }, []);

  const handleHover = useCallback((text: string, rect: DOMRect) => {
    const maxX = typeof window !== 'undefined' ? window.innerWidth - 328 : rect.right + 8;
    setHoverTip({
      text,
      x: Math.max(8, Math.min(rect.right + 8, maxX)),
      y: rect.top + rect.height / 2,
    });
  }, []);

  const handleLeave = useCallback(() => {
    setHoverTip(null);
  }, []);

  const handleSelect = useCallback(
    async (node: ZipTreeNode) => {
      if (!zip || node.isDir || selected?.path === node.path || selectingPathRef.current === node.path) return;
      selectingPathRef.current = node.path;
      if (selected?.blobUrl) URL.revokeObjectURL(selected.blobUrl);
      setPreviewLoading(true);
      setPreviewError(null);

      try {
        const mime = inferMimeType(node.name);
        const blob = await readZipEntryBlob(zip, node.path, mime !== 'application/octet-stream' ? mime : undefined);
        const blobUrl = URL.createObjectURL(blob);
        setSelected({ path: node.path, name: node.name, size: node.size, blobUrl });
        // 移动端切换到预览 tab
        splitRef.current?.switchTab('right');
      } catch (err) {
        console.error(err);
        setPreviewError('条目读取失败');
      } finally {
        setPreviewLoading(false);
        if (selectingPathRef.current === node.path) selectingPathRef.current = null;
      }
    },
    [zip, selected]
  );

  // Memoize files 数组以避免无限重新渲染
  const previewFiles = useMemo(() => {
    if (!selected) return [];
    return [{ name: selected.name, url: selected.blobUrl, type: inferMimeType(selected.name) }];
  }, [selected]);

  // 暴露接口给父组件（必须在 early return 之前调用）
  useImperativeHandle(ref, () => ({
    getToolbarGroups: () => [],
  }), []);

  if (loading) {
    return (
      <div className="rfp-flex rfp-items-center rfp-justify-center rfp-w-full rfp-h-full">
        <div className="rfp-w-12 rfp-h-12 rfp-border-4 rfp-border-line-strong rfp-border-t-spinner-head rfp-rounded-full rfp-animate-spin" />
      </div>
    );
  }

  if (error || !tree) {
    return <RendererError message={error || t('zip.parse_failed')} />;
  }

  // 左侧：文件树
  const leftPane = (
    <div className="rfp-w-full rfp-h-full rfp-overflow-auto">
      {tree.children?.map((child) => (
        <TreeItem
          key={child.path}
          node={child}
          depth={0}
          selectedPath={selected?.path ?? null}
          expanded={expanded}
          onToggle={handleToggle}
          onSelect={handleSelect}
          onHover={handleHover}
          onLeave={handleLeave}
        />
      ))}
    </div>
  );

  // 右侧：预览区
  const rightPane = (
    <div className="rfp-w-full rfp-h-full rfp-flex rfp-flex-col">
      {!selected && (
        <div className="rfp-flex-1 rfp-flex rfp-items-center rfp-justify-center rfp-text-fg-muted rfp-text-sm rfp-p-6">
          从左侧选择一个文件以预览
        </div>
      )}
      {selected && previewLoading && (
        <div className="rfp-flex-1 rfp-flex rfp-items-center rfp-justify-center">
          <div className="rfp-w-8 rfp-h-8 rfp-border-4 rfp-border-line-strong rfp-border-t-spinner-head rfp-rounded-full rfp-animate-spin" />
        </div>
      )}
      {selected && !previewLoading && previewError && (
        <div className="rfp-flex-1 rfp-flex rfp-items-center rfp-justify-center rfp-text-fg-secondary">
          {previewError}
        </div>
      )}
      {selected && !previewLoading && !previewError && (
        <>
          <div className="rfp-flex-1 rfp-min-h-0 rfp-overflow-hidden rfp-flex rfp-relative rfp-z-0">
            <Suspense
              fallback={
                <div className="rfp-flex-1 rfp-flex rfp-items-center rfp-justify-center">
                  <div className="rfp-w-8 rfp-h-8 rfp-border-4 rfp-border-line-strong rfp-border-t-spinner-head rfp-rounded-full rfp-animate-spin" />
                </div>
              }
            >
              <LazyFilePreviewContent
                mode="embed"
                files={previewFiles}
                currentIndex={0}
                zipNestingDepth={nestingDepth + 1}
              />
            </Suspense>
          </div>
        </>
      )}
    </div>
  );

  return (
    <>
      <ResizableSplit
        ref={splitRef}
        left={leftPane}
        right={rightPane}
        initialLeftWidth={280}
        minLeftWidth={180}
        maxLeftWidth={560}
        storageKey="rfp-zip-split-left"
        mobileTabMode
        leftTabLabel="文件树"
        rightTabLabel="预览"
      />
      {/* 文件名 hover tooltip（portal 到 body，避免被滚动区裁剪） */}
      {hoverTip &&
        typeof document !== 'undefined' &&
        createPortal(
          <div
            className="rfp-zip-tip"
            style={{
              position: 'fixed',
              zIndex: 2147483647,
              pointerEvents: 'none',
              padding: '4px 8px',
              background: 'rgba(0, 0, 0, 0.85)',
              color: '#fff',
              fontSize: '12px',
              lineHeight: 1.5,
              borderRadius: '4px',
              whiteSpace: 'nowrap',
              maxWidth: 'min(320px, calc(100vw - 16px))',
              overflow: 'hidden',
              textOverflow: 'ellipsis',
              left: `${hoverTip.x}px`,
              top: `${hoverTip.y}px`,
              transform: 'translateY(-50%)',
            }}
          >
            {hoverTip.text}
          </div>,
          document.body
        )}
    </>
  );
});
