// packages/angular-file-preview/src/renderers/Text/index.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  inject,
  input,
  signal,
} from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
import { WrapText, Code, Eye } from 'lucide-angular';
import { getLanguageFromFileName, fetchTextUtf8 } from '../../fp-core';
import { LocaleService, getFallbackTranslator } from '../../di/locale.service';
import { RequestService } from '../../di/request.service';
import { RendererError } from '../RendererError';
import { ToolbarEventEmitter } from '../base.types';
import type { RendererHandle } from '../base.types';
import type { ToolbarGroup } from '../toolbar.types';
import { createShikiHighlight } from '../../utils/shiki-highlight';

@Component({
  selector: 'afp-text-renderer',
  standalone: true,
  imports: [RendererError],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'afp-block afp-w-full afp-h-full' },
  template: `
    @if (loading() || (language() !== 'text' && highlightLoading())) {
      <div class="afp-flex afp-items-center afp-justify-center afp-w-full afp-h-full">
        <div class="afp-w-12 afp-h-12 afp-border-4 afp-border-line-strong afp-border-t-spinner-head afp-rounded-full afp-animate-spin"></div>
      </div>
    } @else if (error()) {
      <afp-renderer-error [message]="error()!" />
    } @else if (htmlPreview() && language() === 'html') {
      <div class="afp-w-full afp-h-full afp-bg-surface-toolbar">
        <iframe
          [srcdoc]="content()"
          sandbox="allow-same-origin"
          class="afp-w-full afp-h-full afp-border-0"
          [title]="fileName()"
        ></iframe>
      </div>
    } @else if (language() === 'text' || lineHtmls().length === 0) {
      <div class="afp-w-full afp-h-full afp-overflow-auto" style="background: var(--fp-code-bg);">
        <pre
          class="afp-py-6 afp-px-4 afp-text-fg-primary afp-font-mono afp-text-sm"
          [class.afp-whitespace-pre-wrap]="wordWrap()"
          [class.afp-break-words]="wordWrap()"
          [class.afp-whitespace-pre]="!wordWrap()"
        >{{ content() }}</pre>
      </div>
    } @else {
      <div class="afp-w-full afp-h-full afp-overflow-auto" style="background: var(--fp-code-bg);">
        <div
          class="afp-code-block with-line-numbers afp-w-full"
          [class.no-wrap]="!wordWrap()"
          [style.gridTemplateRows]="'repeat(' + lines().length + ', auto) minmax(1.5rem, 1fr)'"
        >
          @for (line of lines(); track $index) {
            <span class="afp-code-gutter">{{ $index + 1 }}</span>
            <span class="afp-code-line" [innerHTML]="trust(lineHtmls()[$index] ?? '')"></span>
          }
          <span class="afp-code-gutter-filler"></span>
          <span class="afp-code-line-filler"></span>
        </div>
      </div>
    }
  `,
})
export class TextRenderer implements RendererHandle {
  url = input.required<string>();
  fileName = input.required<string>();

  private readonly emitter = new ToolbarEventEmitter();
  private readonly locale = inject(LocaleService, { optional: true });
  private readonly request = inject(RequestService, { optional: true });
  private readonly sanitizer = inject(DomSanitizer);
  private readonly t = this.locale?.t() ?? getFallbackTranslator();

  readonly wordWrap = signal(true);
  readonly htmlPreview = signal(false);
  readonly content = signal('');
  readonly loading = signal(true);
  readonly error = signal<string | null>(null);

  readonly language = computed(() => getLanguageFromFileName(this.fileName()));
  readonly isHtml = computed(() => this.language() === 'html');
  readonly lines = computed(() => this.content().split('\n'));

  private readonly shiki = createShikiHighlight(
    () => (this.language() !== 'text' ? this.content() : ''),
    () => this.language(),
  );
  readonly lineHtmls = this.shiki.lineHtmls;
  readonly highlightLoading = this.shiki.loading;

  constructor() {
    effect(() => {
      this.url();
      void this.loadText();
    });
    effect(() => {
      this.content();
      this.language();
      void this.shiki.highlight();
    });
    effect(() => {
      this.wordWrap();
      this.htmlPreview();
      this.loading();
      this.isHtml();
      this.emitter.notify();
    });
  }

  getToolbarGroups = (): ToolbarGroup[] => {
    const groups: ToolbarGroup[] = [
      {
        items: [
          {
            type: 'button',
            icon: WrapText,
            tooltip: this.wordWrap() ? this.t('toolbar.wrap_off') : this.t('toolbar.wrap_on'),
            action: () => this.wordWrap.update((v) => !v),
            active: this.wordWrap(),
          },
        ],
      },
    ];
    if (this.isHtml()) {
      groups.push({
        items: [
          {
            type: 'button',
            icon: this.htmlPreview() ? Code : Eye,
            tooltip: this.htmlPreview() ? this.t('toolbar.source') : this.t('toolbar.preview'),
            action: () => this.htmlPreview.update((v) => !v),
            active: this.htmlPreview(),
          },
        ],
      });
    }
    return groups;
  };

  onToolbarChange = (listener: () => void) => this.emitter.subscribe(listener);

  protected trust(html: string) {
    return this.sanitizer.bypassSecurityTrustHtml(html);
  }

  private async loadText(): Promise<void> {
    this.loading.set(true);
    this.error.set(null);
    try {
      const fetcher = this.request?.fetcher() ?? ((u: string, init?: RequestInit) => fetch(u, init));
      const text = await fetchTextUtf8(this.url(), { fetcher });
      this.content.set(text);
    } catch (err) {
      console.error(err);
      this.error.set(this.t('text.load_failed'));
    } finally {
      this.loading.set(false);
    }
  }
}

// packages/vue-file-preview/src/renderers/Text/index.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { WrapText, Code, Eye } from 'lucide-vue-next';
import { getLanguageFromFileName, fetchTextUtf8 } from '@eternalheart/file-preview-core';
import { useTranslator } from '../../composables/useTranslator';
import { useFetcher } from '../../composables/useRequest';
import { useShikiHighlight } from '../../composables/useShikiHighlight';
import RendererError from '../RendererError.vue';
import { ToolbarEventEmitter } from '../base.types';
import type { RendererHandle } from '../base.types';
import type { ToolbarGroup } from '../toolbar.types';

const props = defineProps<{
  url: string;
  fileName: string;
}>();

const emitter = new ToolbarEventEmitter();

const { t } = useTranslator();
const fetcher = useFetcher();

// 内部状态
const wordWrap = ref(true);
const htmlPreview = ref(false);

const content = ref<string>('');
const loading = ref(true);
const error = ref<string | null>(null);

const language = computed(() => getLanguageFromFileName(props.fileName));
const codeForShiki = computed(() => (language.value !== 'text' ? content.value : ''));
const { lineHtmls, loading: highlightLoading } = useShikiHighlight(codeForShiki, language);

const isHtml = computed(() => language.value === 'html');

// 监听状态变化，通知工具栏更新
watch([wordWrap, htmlPreview, loading, isHtml], () => {
  emitter.notify();
});

const loadText = async () => {
  loading.value = true;
  error.value = null;
  try {
    const text = await fetchTextUtf8(props.url, { fetcher: fetcher.value });
    content.value = text;
  } catch (err) {
    console.error(err);
    error.value = t.value('text.load_failed');
  } finally {
    loading.value = false;
  }
};

watch(() => props.url, loadText, { immediate: true });

const lines = computed(() => content.value.split('\n'));

// 工具栏配置（对齐 React：WrapText 图标固定、Code/Eye 图标、翻译 key）
const getToolbarGroups = (): ToolbarGroup[] => {
  const groups: ToolbarGroup[] = [];

  groups.push({
    items: [
      {
        type: 'button',
        icon: WrapText,
        tooltip: wordWrap.value ? t.value('toolbar.wrap_off') : t.value('toolbar.wrap_on'),
        action: () => { wordWrap.value = !wordWrap.value; },
        active: wordWrap.value,
      },
    ],
  });

  if (isHtml.value) {
    groups.push({
      items: [
        {
          type: 'button',
          icon: htmlPreview.value ? Code : Eye,
          tooltip: htmlPreview.value ? t.value('toolbar.source') : t.value('toolbar.preview'),
          action: () => { htmlPreview.value = !htmlPreview.value; },
          active: htmlPreview.value,
        },
      ],
    });
  }

  return groups;
};

defineExpose<RendererHandle>({
  getToolbarGroups,
  onToolbarChange: (listener) => emitter.subscribe(listener),
});
</script>

<template>
  <div v-if="loading || (language !== 'text' && highlightLoading)" class="vfp-flex vfp-items-center vfp-justify-center vfp-w-full vfp-h-full">
    <div
      class="vfp-w-12 vfp-h-12 vfp-border-4 vfp-border-line-strong vfp-border-t-spinner-head vfp-rounded-full vfp-animate-spin"
    />
  </div>

  <RendererError v-else-if="error" :message="error" />

  <!-- HTML 预览模式 -->
  <div v-else-if="htmlPreview && language === 'html'" class="vfp-w-full vfp-h-full vfp-bg-surface-toolbar">
    <iframe
      :srcdoc="content"
      sandbox="allow-same-origin"
      class="vfp-w-full vfp-h-full vfp-border-0"
      :title="fileName"
    />
  </div>

  <!-- 纯文本或高亮未就绪：fallback -->
  <div v-else-if="language === 'text' || lineHtmls.length === 0" class="vfp-w-full vfp-h-full vfp-overflow-auto" style="background: var(--fp-code-bg);">
    <pre
      class="vfp-py-6 vfp-px-4 vfp-text-fg-primary vfp-font-mono vfp-text-sm"
      :class="wordWrap ? 'vfp-whitespace-pre-wrap vfp-break-words' : 'vfp-whitespace-pre'"
    >{{ content }}</pre>
  </div>

  <!-- 双列布局：左 gutter（行号），右 code（shiki 高亮） -->
  <div v-else class="vfp-w-full vfp-h-full vfp-overflow-auto" style="background: var(--fp-code-bg);">
    <div
      class="vfp-code-block with-line-numbers vfp-w-full"
      :class="{ 'no-wrap': !wordWrap }"
      :style="{ gridTemplateRows: `repeat(${lines.length}, auto) minmax(1.5rem, 1fr)` }"
    >
      <template v-for="(_, i) in lines" :key="i">
        <span class="vfp-code-gutter">{{ i + 1 }}</span>
        <span class="vfp-code-line" v-html="lineHtmls[i] ?? ''" />
      </template>
      <!-- 占位行：撑满剩余高度，让 gutter border 延伸到底部 -->
      <span class="vfp-code-gutter-filler" />
      <span class="vfp-code-line-filler" />
    </div>
  </div>
</template>
